# Generated by Django 3.2 on 2021-04-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
